name: ud_widgets
description: A flutter package with collection of simplified widgets that will make your application development faster. We used flutter widgets and customized in a way so that you can easily use them.
version: 0.0.1
homepage: https://github.com/shajedulislam/ud_widgets

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter