name: ud_widgets
description: Collection of simplified widgets that will make your application development easy and faster.
version: 0.3.1
homepage: https://github.com/shajedulislam/ud_widgets

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.21.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter